// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reuyjwtdaxjjthgmfmbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJldXlqd3RkYXhqanRoZ21mbWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NjkyMzEsImV4cCI6MjA1MjU0NTIzMX0.XyW3bMBq5lnFLrJeWdAJ8SAgX_S-f5JFKVMmAxbMle4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);